apiVersion: apps/v1
kind: Deployment
metadata:
  name: cellpay-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cellpay
  template:
    metadata:
      labels:
        app: cellpay
    spec:
      containers:
      - name: cellpay-container
        image: 682033476070.dkr.ecr.eu-north-1.amazonaws.com/cellpay-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: cellpay-service
spec:
  type: NodePort
  selector:
    app: cellpay
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30036
